BEGIN TRANSACTION
UPDATE WORKITEMS_WORKITEMS 
SET WI_FORMFIELDS=(SELECT WI_FORMFIELDS FROM WORKITEMS_WORKITEMS AS W WHERE W.WORKITEM=WORKITEMS_WORKITEMS.WI_PREVID)
WHERE WI_FORMFIELDS LIKE '%REQUESTLIST%'
ROLLBACK TRANSACTION
SELECT * FROM WORKITEMS_WORKITEMS WHERE WORKITEM IN(
1274,
1277,
1285,
1290,
1291)
COMMIT
